language: node_js
node_js:
  - "0.12"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2599e8eaaec09f124f11
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
